/******************************************************
* Autogenerated code created by the ConsoleBuilder    *
*   https://github.com/embedCreativity/ConsoleBuilder *
*                                                     *
* Generated on: CODE_GENERATION_DATE            *
******************************************************/

#ifndef FILENAME_PLACEHOLDER_H_

// General Dependencies
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>

// method forward declarations
METHOD_FUNC_FORWARD_DECLARATIONS

#endif // FILENAME_PLACEHOLDER_H_
