/******************************************************
* Autogenerated code created by the ConsoleBuilder    *
*   https://github.com/embedCreativity/ConsoleBuilder *
*                                                     *
* Generated on: CODE_GENERATION_DATE            *
******************************************************/

EXTERNAL_HEADER
EXAMPLE_PARSING_ROUTINES
/************************************************************************************/
/* Console Methods                                                                  */
/************************************************************************************/
FUNCTION_STUBS
